/**
 * Single source of truth for first-path segments that are app routes, not usernames.
 * Used by: (public)/[username] routing, App.tsx routeFromPathname, claim/safeSlug validation.
 * When adding a new top-level route, add it here and run scripts/checkReservedCollisions.ts.
 */
export const RESERVED_PATHS = new Set([
  "app",
  "api",
  "auth",
  "login",
  "signup",
  "dashboard",
  "settings",
  "analytics",
  "xspaces",
  "calendar",
  "explore",
  "terms",
  "privacy-policy",
  "privacy",
  "onboarding",
  "profile",
  "overview",
  "market",
  "messages",
  "circles",
  "verification",
  "pricing",
  "billing",
  "plans",
  "test-supabase",
  "home",
  "leaderboards",
  "creator",
  "brand",
  "agency",
  "host",
  "availability",
  "monetization",
  "monetization-flow",
  "kol-lists",
  "capital-partners",
  "connections",
  "preferences",
  "support",
  "notifications",
  "verification-inbox",
  "showcase",
  "integrations",
  "roles-skills",
  "u",
  "watchlist",
  "work",
  "invites",
  "creator-programs",
  "admin",
  // Static assets / special (first segment only; Next.js may serve these before [username])
  "favicon.ico",
  "robots.txt",
  "sitemap.xml",
]);

export function isReservedPath(segment: string): boolean {
  return RESERVED_PATHS.has(segment.toLowerCase());
}
